### ISSUE TITLE
v0.1.4 and v0.1.6 fails to build for darwin arm64

### ISSUE THREAD

**Issue by mdeggies** [hashicorp/actions-go-build#18]
The two latest releases (since the bash->go refactoring) fail to build darwin arm64 artifacts properly. Pinning to v0.1.3 (for darwin builds) is a current workaround for this issue. There are a lot of commits from v0.1.3 -> v0.1.6, so this has not been an easy one to troubleshoot or fix. I'm setting aside this aside for now, and will plan to reach out to @samsalisbury or @alvin-huang when they're back to troubleshoot further and provide a fix. 

More information from end users is available in https://hashicorp.slack.com/archives/CR024M999/p166629796788295. A link to a failure in crt-core-helloworld is available here: https://github.com/hashicorp/crt-core-helloworld/actions/runs/3296659149.

**Comment by samsalisbury** [comment]
Closed by #20
